server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能,利用微服务名进行路由
      routes:
        - id: payment_get_route #payment_get_route #路由的ID,没有固定规则但要求唯一,建议配合服务名
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**  #断言,路径相匹配的进行路由
            - After=2021-06-29T14:22:29.545+08:00[Asia/Shanghai]

        - id: payment_lb_route #payment_lb_route #路由的ID,没有固定规则但要求唯一,建议配合服务名
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**  #断言,路径相匹配的进行路由
            #- Before=2017-01-20T17:42:47.789-07:00[America/Denver]
            #- After=2021-06-29T14:22:29.545+08:00[Asia/Shanghai]
            #- Between=2017-01-20T17:42:47.789-07:00[America/Denver], 2017-01-21T17:42:47.789-07:00[America/Denver]
            #- Cookie=chocolate, ch.p
            #- Header=X-Request-Id, \d+  #请求头要有X-Request-Id属性并且值为整数的正则表达式
            #- Host=**.somehost.org,**.anotherhost.org
            #- - Method=GET,POST
            #- Query=green, \d+  #要由参数名称green并且值为整数才能路由
            #- RemoteAddr=192.168.1.1/24
            #- Weight=group1, 2
eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka